module: simple_copy_paste
name: SimpleCopyPaste
SimpleCopyPaste:
  background_dir: '''./sample/background/'''
  template_ratio: 'random.uniform(0.4, 0.98)'
  template_type: '''CARD_BACK'''
  image_pattern: '''*.*'''
  fg_optional_transforms:
    - iaa.Affine(rotate=(-20, 20), shear=(-15, 15), fit_output=True)
    - iaa.Rot90(k=[1, 2, 3], keep_size=False)
    - iaa.PerspectiveTransform(scale=(0.01, 0.05), keep_size=False, fit_output=True)
    - iaa.ElasticTransformation(alpha=(0, 0.5), sigma=0.25)
  bg_optional_transforms:
    - iaa.ElasticTransformation(alpha=(0.1, 0.5), sigma=0.25)
    - iaa.ChangeColorTemperature(kelvin=(4000, 9000))
    - iaa.AverageBlur(k=((1, 7), (1, 7)))
    - iaa.MedianBlur(k=(1, 7))
    - iaa.MotionBlur(k=(3, 5))
  output_required_transforms:
    - iaa.GaussianBlur(sigma=(0.0, 2.0))
    - iaa.AverageBlur(k=((1, 7), (1, 7)))
    - iaa.MultiplySaturation((0.5, 1.5))
  output_optional_transforms:
    - iaa.ElasticTransformation(alpha=(0.1, 0.5), sigma=0.25)
    - iaa.ChangeColorTemperature(kelvin=(4000, 9000))
    - iaa.MotionBlur(k=(3, 5))
    # - iaa.MultiplyBrightness((0.0, 1.5))
