blur: [3, 3]
rotate3D:
  theta: [-20, 20]
  phi: [-20, 20] 
  gamma: [0, 0]
  dx: 0
  dy: 0
  dz: 0
rotate2D:
  angle: [-30, 30]
  scale: [1.0, 1.0]
contrast: [-20, 20]
brightness: [-10, 10]
noisy: 0
flip: 0
ratio_hf_per_hb: [0.3, 0.8]
